- name: Prepare setup directory
  ansible.builtin.file:
    path: '/setup'
    state: directory
    recurse: yes

- name: Pre commands
  ansible.builtin.shell:
    cmd: '{{ item }}'
  loop: '{{ potos_firstboot_precommands }}'
  when: 
   - potos_firstboot_precommands is defined
   - potos_firstboot_precommands is iterable
   - potos_firstboot_precommands is not string
   - potos_firstboot_precommands is not mapping

- name: Install yad
  ansible.builtin.package:
    name: 'yad'
    
- name: Yad test
  ansible.builtin.shell:
    executable: '/bin/bash'
    cmd: yad --text 'Demo YAD Window that must open during installation'  --button=gtk-close
