- name: Prepare setup directory
  ansible.builtin.file:
    path: '/setup'
    state: directory
    recurse: yes

- name: Pre commands
  ansible.builtin.shell:
    cmd: '{{ item }}'
  loop: '{{ potos_firstboot_precommands }}'
  when: 
   - potos_firstboot_precommands is defined
   - potos_firstboot_precommands is iterable
   - potos_firstboot_precommands is not string
   - potos_firstboot_precommands is not mapping

- name: Install yad
  ansible.builtin.package:
    name: 'yad'

- name: Ask for keyboard layout
  block:
    - name: deploy script for keyboard layout selection
      ansible.builtin.template:
        src: 'change-keyboard-layout.j2'
        dest: '/setup/change-keyboard-layout2'
        mode: '0755'
        owner: root
        group: root

    - name: ask dialog
      ansible.builtin.shell:
        cmd: '/setup/change-keyboard-layout2'
      register: potos_firstboot_keyboard_layout
      changed_when: false

    - name: check if keyboard file exists
      ansible.builtin.stat:
        path: '/etc/default/keyboard'
      register: potos_firstboot_default_keyboard_stat
    
    - name: set keyboard layout
      ansible.builtin.replace:
        path: '/etc/default/keyboard'
        regexp: 'XKBLAYOUT="\w*"'
        replace: 'XKBLAYOUT="{{ potos_firstboot_keyboard_layout.stdout }}"'
      when: potos_firstboot_default_keyboard_stat.stat.exists

    - name: check if gsettings is installed
      ansible.builtin.shell:
        cmd: 'gsettings help'
      failed_when: false
      changed_when: false
      register: potos_firstboot_gsettings_exists

    - name: set keyboard layout in gnome
      ansible.builtin.shell:
        cmd: "gsettings set org.gnome.desktop.input-sources sources '[(\"xkb\", \"{{ potos_firstboot_keyboard_layout.stdout }}\")]'"
      changed_when: false
      when: potos_firstboot_gsettings_exists.rc == 0
